import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Vanilla Dream",
    description: "Warm vanilla with hints of amber and sandalwood. Perfect for creating a cozy atmosphere in any room.",
    price: 599,
    image: "/images/candles/vanilla-dreams.jpg",
    scent: "Vanilla",
    size: "250g",
    weight: 0.25,
    burnTime: 45,
    inStock: true,
    quantity: 100,
  },
  {
    id: "2",
    name: "Rose Garden",
    description: "Elegant rose blended with jasmine and rose petals. A timeless floral fragrance for sophisticated spaces.",
    price: 649,
    image: "/images/candles/rose-garden.jpg",
    scent: "Rose",
    size: "300g",
    weight: 0.3,
    burnTime: 50,
    inStock: true,
    quantity: 85,
  },
  {
    id: "3",
    name: "Ocean Breeze",
    description: "Fresh sea salt with notes of driftwood and aquatic minerals. Brings the essence of the ocean to your home.",
    price: 599,
    image: "/images/candles/ocean-breeze.jpg",
    scent: "Ocean",
    size: "250g",
    weight: 0.25,
    burnTime: 45,
    inStock: true,
    quantity: 120,
  },
  {
    id: "4",
    name: "Lavender Serenity",
    description: "Calming lavender with chamomile and lavender buds. Ideal for relaxation and meditation spaces.",
    price: 549,
    image: "/images/candles/lavender-bliss.jpg",
    scent: "Lavender",
    size: "200g",
    weight: 0.2,
    burnTime: 40,
    inStock: true,
    quantity: 95,
  },
  {
    id: "5",
    name: "Cinnamon Spice",
    description: "Warm cinnamon with clove and nutmeg undertones. Creates a festive and inviting ambiance.",
    price: 599,
    image: "/images/candles/cinnamon-spice.jpg",
    scent: "Spice",
    size: "250g",
    weight: 0.25,
    burnTime: 45,
    inStock: true,
    quantity: 110,
  },
  {
    id: "6",
    name: "Sandalwood Luxury",
    description: "Premium sandalwood with oud and musk. A luxurious blend for refined taste.",
    price: 699,
    image: "/images/candles/sandalwood-serenity.jpg",
    scent: "Sandalwood",
    size: "300g",
    weight: 0.3,
    burnTime: 50,
    inStock: true,
    quantity: 60,
  },
  {
    id: "7",
    name: "Citrus Sunshine",
    description: "Bright citrus blend with lemon, orange, and bergamot. Energy and positivity in every burn.",
    price: 549,
    image: "/images/candles/citrus-burst.jpg",
    scent: "Citrus",
    size: "200g",
    weight: 0.2,
    burnTime: 40,
    inStock: true,
    quantity: 130,
  },
  {
    id: "8",
    name: "Eucalyptus Mint",
    description: "Refreshing eucalyptus with cool mint and herbal notes. An earthy escape to a spa retreat.",
    price: 599,
    image: "/images/candles/eucalyptus-mint.jpg",
    scent: "Herbal",
    size: "250g",
    weight: 0.25,
    burnTime: 45,
    inStock: true,
    quantity: 105,
  },
  {
    id: "9",
    name: "Jasmine Night",
    description: "Mysterious jasmine with night-blooming florals and soft musk. Perfect for evening ambiance.",
    price: 649,
    image: "/images/candles/jasmine-night.jpg",
    scent: "Floral",
    size: "280g",
    weight: 0.28,
    burnTime: 48,
    inStock: true,
    quantity: 75,
  },
  {
    id: "10",
    name: "Fresh Linen",
    description: "Clean fresh linen with cotton blossom and soft musk. Warmth and freshness combined.",
    price: 599,
    image: "/images/candles/fresh-linen.jpg",
    scent: "Fresh",
    size: "250g",
    weight: 0.25,
    burnTime: 45,
    inStock: true,
    quantity: 90,
  },
];
